# Generated by Django 3.1.3 on 2020-12-02 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='last_description',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='last_driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='utils.driver'),
        ),
        migrations.AddField(
            model_name='order',
            name='last_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='utils.state'),
        ),
        migrations.AddField(
            model_name='order',
            name='last_provider',
            field=models.ForeignKey(default='4fd1d932-f86a-456b-9f39-f9919ad22040', on_delete=django.db.models.deletion.CASCADE, to='utils.provider'),
        ),
        migrations.AddField(
            model_name='order',
            name='last_status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='utils.status'),
        ),
        migrations.AlterField(
            model_name='orderstatus',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='utils.state'),
        ),
    ]
