# Generated by Django 3.0.3 on 2020-04-15 18:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
        ('tasks', '0002_auto_20200221_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='assignee',
        ),
        migrations.RemoveField(
            model_name='order',
            name='client_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='prov_id',
        ),
        migrations.RemoveField(
            model_name='origin',
            name='address',
        ),
        migrations.AddField(
            model_name='destination',
            name='ap_unit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='house_num',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='street',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='suburb',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='client',
            field=models.ForeignKey(default='NA', on_delete=django.db.models.deletion.CASCADE, to='utils.Client', to_field='client_code'),
        ),
        migrations.AddField(
            model_name='origin',
            name='ap_unit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='origin',
            name='house_num',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='origin',
            name='street',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='origin',
            name='suburb',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='destination',
            name='city',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='destination',
            name='latitude',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='destination',
            name='longitude',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='accidental_delivery_duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='delay',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='duration',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='origin',
            name='city',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='origin',
            name='latitude',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='origin',
            name='longitude',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=150, null=True)),
                ('st_update', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='utils.State')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ord_status', to='tasks.Order')),
                ('provider', models.ForeignKey(default='PG', on_delete=django.db.models.deletion.CASCADE, to='utils.Provider', to_field='prov_code')),
                ('status', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='utils.Status')),
            ],
        ),
        migrations.CreateModel(
            name='OrderPackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)])),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='tasks.Order')),
                ('pak_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='utils.Package')),
            ],
        ),
    ]
