# Generated by Django 3.0.5 on 2020-04-24 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
        ('tasks', '0003_auto_20200415_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='city',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='destination',
            name='house_num',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='destination',
            name='pos_code',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='destination',
            name='street',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='orderstatus',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='utils.Status'),
        ),
        migrations.AlterField(
            model_name='origin',
            name='city',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='origin',
            name='pos_code',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='origin',
            name='street',
            field=models.CharField(max_length=100),
        ),
    ]
