# Generated by Django 2.2.5 on 2020-01-23 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20200123_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='accidental_delivery_duration',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='task',
            name='assignee',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='delay',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='duration',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='latitude',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='longitude',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='request_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='start_time',
            field=models.DateField(null=True),
        ),
    ]
