# Generated by Django 3.1.3 on 2021-04-05 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20210304_1800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderpackage',
            name='pack_price',
        ),
        migrations.AlterField(
            model_name='destination',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='destination',
            name='street',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='destination',
            name='suburb',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='origin',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='origin',
            name='street',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='origin',
            name='suburb',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
