# Generated by Django 3.1.3 on 2021-04-05 19:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_auto_20210405_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderpackage',
            name='height',
            field=models.PositiveIntegerField(default=0, verbose_name='Height in mm'),
        ),
        migrations.AlterField(
            model_name='orderpackage',
            name='length',
            field=models.PositiveIntegerField(default=0, verbose_name='Length in mm'),
        ),
        migrations.AlterField(
            model_name='orderpackage',
            name='quantity',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(99)]),
        ),
        migrations.AlterField(
            model_name='orderpackage',
            name='width',
            field=models.PositiveIntegerField(default=0, verbose_name='Width in mm'),
        ),
    ]
