# Generated by Django 3.0.5 on 2020-04-27 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
        ('tasks', '0004_auto_20200424_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstatus',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='utils.State', to_field='state_name'),
        ),
    ]
