# Generated by Django 3.1.3 on 2021-04-06 17:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_auto_20210405_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderpackage',
            name='package_id',
            field=models.CharField(default='AAAA000000-00', max_length=13, validators=[django.core.validators.RegexValidator(code='nomatch', message='Length has to be 13', regex='^.[A-Z]{4}[0-9]{6}-[0-9]{2}$')]),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='AAAA000000', max_length=10, validators=[django.core.validators.RegexValidator(code='nomatch', message='Length has to be 10', regex='^[A-Z]{4}[0-9]{6}$')]),
        ),
    ]
