# Generated by Django 3.0.2 on 2020-02-07 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_task_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='address',
        ),
        migrations.RemoveField(
            model_name='task',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='task',
            name='longitude',
        ),
        migrations.AddField(
            model_name='task',
            name='client_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='prov_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='request_id',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='Origin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('latitude', models.CharField(max_length=50)),
                ('longitude', models.CharField(max_length=50)),
                ('pos_code', models.IntegerField(null=True)),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.Task')),
            ],
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('latitude', models.CharField(max_length=50)),
                ('longitude', models.CharField(max_length=50)),
                ('pos_code', models.IntegerField(null=True)),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.Task')),
            ],
        ),
    ]
