# Generated by Django 3.0.5 on 2020-04-30 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
        ('tasks', '0005_auto_20200427_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utils.Client'),
        ),
        migrations.AlterField(
            model_name='orderstatus',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='utils.State'),
        ),
    ]
