# Generated by Django 3.0.5 on 2020-05-05 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0002_auto_20200430_2031'),
        ('tasks', '0006_auto_20200430_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstatus',
            name='provider',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='utils.Provider'),
        ),
    ]
