# Generated by Django 3.0.5 on 2020-05-14 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_auto_20200505_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='country',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='origin',
            name='country',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
