# Generated by Django 3.0.5 on 2020-06-01 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_auto_20200514_0905'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='province',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='origin',
            name='province',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='destination',
            name='city',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='origin',
            name='city',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
