# Generated by Django 3.0.2 on 2020-02-08 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_auto_20200208_0517'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destination',
            old_name='task_id',
            new_name='task',
        ),
        migrations.RenameField(
            model_name='origin',
            old_name='task_id',
            new_name='task',
        ),
    ]
