# Generated by Django 3.0.5 on 2020-06-05 18:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_auto_20200601_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ord_price',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='orderpackage',
            name='ord_pak_price',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='order',
            name='accidental_delivery_duration',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='duration',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
