# Generated by Django 3.0.5 on 2020-06-05 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_auto_20200605_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='destination',
            name='street',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='origin',
            name='city',
            field=models.CharField(default='Córdoba', max_length=50),
        ),
        migrations.AlterField(
            model_name='origin',
            name='country',
            field=models.CharField(default='Argentina', max_length=50),
        ),
        migrations.AlterField(
            model_name='origin',
            name='house_num',
            field=models.IntegerField(default=2199, null=True),
        ),
        migrations.AlterField(
            model_name='origin',
            name='latitude',
            field=models.CharField(default='-31.383496', max_length=50),
        ),
        migrations.AlterField(
            model_name='origin',
            name='longitude',
            field=models.CharField(default='-64.127273', max_length=50),
        ),
        migrations.AlterField(
            model_name='origin',
            name='name',
            field=models.CharField(default='Deposito PackGo', max_length=50),
        ),
        migrations.AlterField(
            model_name='origin',
            name='province',
            field=models.CharField(default='Córdoba', max_length=50),
        ),
        migrations.AlterField(
            model_name='origin',
            name='street',
            field=models.CharField(default='Alvarez de Condarco', max_length=50),
        ),
    ]
