# Generated by Django 3.0.2 on 2020-02-08 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_auto_20200208_0552'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destination',
            old_name='task',
            new_name='task_id',
        ),
        migrations.RenameField(
            model_name='origin',
            old_name='task',
            new_name='task_id',
        ),
    ]
