# Generated by Django 3.0.5 on 2020-06-09 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0012_driver'),
        ('tasks', '0012_auto_20200605_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderstatus',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='utils.Driver'),
        ),
    ]
