# Generated by Django 3.0.5 on 2020-06-10 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_orderstatus_driver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='pos_code',
            field=models.IntegerField(blank=True),
        ),
    ]
