# Generated by Django 3.0.2 on 2020-02-10 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0016_auto_20200210_1326'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destination',
            old_name='task',
            new_name='t_id',
        ),
        migrations.RenameField(
            model_name='origin',
            old_name='task',
            new_name='t_id',
        ),
    ]
