# Generated by Django 3.0.5 on 2020-06-11 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0016_auto_20200610_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='house_num',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='destination',
            name='street',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='origin',
            name='house_num',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='origin',
            name='street',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
