# Generated by Django 3.0.5 on 2020-06-12 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0017_auto_20200611_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='request_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
