# Generated by Django 3.0.5 on 2020-04-30 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='status_desc',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
