# Generated by Django 3.1.3 on 2021-04-05 14:22

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='pkg_coef',
        ),
        migrations.RemoveField(
            model_name='package',
            name='pkg_fixed',
        ),
        migrations.AddField(
            model_name='client',
            name='distance_coef',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Distance Coefficient'),
        ),
        migrations.AlterField(
            model_name='client',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Client ID'),
        ),
        migrations.AlterField(
            model_name='package',
            name='height',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Height in mm'),
        ),
        migrations.AlterField(
            model_name='package',
            name='length',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Length in mm'),
        ),
        migrations.AlterField(
            model_name='package',
            name='pkg_code',
            field=models.CharField(max_length=2, unique=True, verbose_name='Package Code'),
        ),
        migrations.AlterField(
            model_name='package',
            name='pkg_description',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Package Description'),
        ),
        migrations.AlterField(
            model_name='package',
            name='pkg_name',
            field=models.CharField(max_length=20, unique=True, verbose_name='Package Name'),
        ),
        migrations.AlterField(
            model_name='package',
            name='volume',
            field=models.FloatField(default=0, editable=False, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Volume in m3'),
        ),
        migrations.AlterField(
            model_name='package',
            name='weight',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Weight in kg'),
        ),
        migrations.AlterField(
            model_name='package',
            name='width',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Width in mm'),
        ),
    ]
