# Generated by Django 3.1.3 on 2021-04-05 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0002_auto_20210405_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='height',
            field=models.PositiveIntegerField(default=0, verbose_name='Height in mm'),
        ),
        migrations.AlterField(
            model_name='package',
            name='length',
            field=models.PositiveIntegerField(default=0, verbose_name='Length in mm'),
        ),
        migrations.AlterField(
            model_name='package',
            name='volume',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Volume in m3'),
        ),
        migrations.AlterField(
            model_name='package',
            name='weight',
            field=models.PositiveIntegerField(default=0, verbose_name='Weight in kg'),
        ),
        migrations.AlterField(
            model_name='package',
            name='width',
            field=models.PositiveIntegerField(default=0, verbose_name='Width in mm'),
        ),
    ]
