# Generated by Django 3.1.3 on 2021-04-05 14:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0003_auto_20210405_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='volume',
            field=models.FloatField(default=0, editable=False, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Volume in m3'),
        ),
    ]
