# Generated by Django 3.0.5 on 2020-06-01 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0004_auto_20200601_1415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='state',
            name='state',
        ),
    ]
