# Generated by Django 3.0.5 on 2020-06-01 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0005_remove_state_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='latitude',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='state',
            name='longitude',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
