# Generated by Django 3.0.5 on 2020-06-03 19:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0008_auto_20200603_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='price_disc',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
    ]
