# Generated by Django 3.0.5 on 2020-06-05 18:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0010_auto_20200603_1610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='price',
        ),
        migrations.AddField(
            model_name='package',
            name='pkg_coef',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='package',
            name='pkg_price',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
