# Generated by Django 3.0.5 on 2020-06-09 13:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0011_auto_20200605_1514'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driv_name', models.CharField(max_length=20, unique=True)),
                ('vehicle_type', models.CharField(max_length=20)),
                ('vehicle_brand', models.CharField(blank=True, max_length=30, null=True)),
                ('vehicle_model', models.CharField(blank=True, max_length=30, null=True)),
                ('vehicle_year', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(2999)])),
                ('vehicle_plate', models.CharField(max_length=20, unique=True)),
                ('vehicle_capacity', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prov_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='utils.Provider')),
            ],
        ),
    ]
